### ISSUE TITLE
filtering response HTML - how to get the instance of the form?

### ISSUE THREAD

**Issue by nimmolo** [ibericode/mc4wp-snippets#5]
Hi Danny, thanks for this plugin. 

I've read up on the MC4WP hook, but i'm missing something. 
`apply_filters ( 'mc4wp_form_response_html', string $html, MC4WP_Form $form )`

I can't figure out how to get the instance of the form to pass to this filter. 

I've tried using `MC4WP_Form::get_instance();` ... i'm sure i'm missing something obvious. 
Sorry to bother you.

**Comment by dannyvankooten** [comment]
Hi @nimmolo ,

The `MC4WP_Form` instance is the second argument passed to the filter callback. So you can use it like this:

```php
add_filter( 'mc4wp_form_response_html', function( $html, $form ) {
     // here you have access to both $html and $form
}, 10, 2 );
```

Please note the 4th parameter `2`, which tells the `add_filter` function that our callback accepts 2 arguments. Otherwise only one will be passed.

Hope that helps. If not, let me know!
